# Generated by Django 2.2.17 on 2021-05-27 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=180)),
                ('text', models.CharField(max_length=280)),
                ('category', models.CharField(default='Другое', max_length=30)),
                ('user', models.CharField(max_length=20)),
                ('time', models.IntegerField(default=1622144050.1324234)),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Commentary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=280, null=True)),
                ('time', models.IntegerField(default=1622144050)),
                ('theory', models.BooleanField(default=False)),
                ('rating', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='dispute_site.Question')),
            ],
        ),
    ]
